// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    S3_REGION: string;
    S3_ACCESS_ID: string;
    S3_SECRET_KEY: string;
    S3_ENDPOINT: string;
    S3_BUCKET: string;
    NEXT_PUBLIC_S3_HOST_NAME: string;
    WRANGLER_BUILD_CONDITIONS: string;
    WRANGLER_BUILD_PLATFORM: string;
    SLIDES: R2Bucket;
    ASSETS: Fetcher;
}
